### PR TITLE
Fix #162 Implement Auto-Save Feature for Form Fields

### LINKED ISSUE #162: ⚡️Auto-save on all forms, when data is filled
💭 Introduction
This task aims at improving user experience by enabling auto save while adding data in form fields. Currently user needs to click on edit option besides a field and also click on save option once he/she is done with entering the data. For viewing a sample form, you can click on Testing section, and click on Create Button in "Automate attacker auth token generation" section. The task involves modifying this behaviour where User should now be able to click on a field and fill respective data which will keep getting auto saved. 

🎯 Requirements
Vue.js
React

✅ Task summary:

- [ ] Ask to be assigned to the issue.
- [ ] Wait to be assigned. We will try to assign in less than 2 hours.
- [ ] Modify the logic in TemplateStringEditor.jsx, and respective vue.js files and test out a sample form.
- [ ] Submit a pull request here.

✌🏻 Hints
Currently this logic is present in TemplateStringEditor.jsx, which is being used in multiple places for building forms in vue.js files (check for template-string-editor)

🙋🏼‍♂️ Questions:
If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://discord.com/invite/Wpc6xVME4s).

### PR DESCRIPTION
**Pull request by adarsh-jha-dev**
Reopened #677 with corrections, fixes #162

### CODE REVIEW

**Comment by avneesh-akto** [comment]
Please change target branch from master to develop

**Comment by adarsh-jha-dev** [comment]
> Please change target branch from master to develop

Done

**Comment by adarsh-jha-dev** [comment]
> Please change target branch from master to develop

Hey @avneesh-akto , is there any update on this PR, i request you to please review this and let me know if the changes are relevant

**Comment by avneesh-akto** [comment]
Hi @adarsh-jha-dev we are looking into it. Give us some time please

**Comment by adarsh-jha-dev** [comment]
> Hi @adarsh-jha-dev we are looking into it. Give us some time please

@avneesh-akto , is there any update on this PR?

**Comment by adarsh-jha-dev** [comment]
> > Hi @adarsh-jha-dev we are looking into it. Give us some time please
> 
> @avneesh-akto , is there any update on this PR?

Hey @avneesh-akto , is there any change needed? I request you to please reply anything for this PR, It is in the queue for a long time.

**Comment by ankush-jain-akto** [comment]
Closing this. This isn't working. We should use Zustand or at least set `storageKey` in all its callers

**Pull request closed without merging**
