### PR TITLE
Fixed the link to "LICENSE.md" file

### PR DESCRIPTION
**Pull request by adarsh-jha-dev**
The previous link of the file LICENSE.md" was giving 404 error, i fixed it by correcting the link.

### CODE REVIEW

**Comment by avneesh-akto** [comment]
LGTM. Thank you for the submission. Can you edit the PR to develop branch?

**Comment by adarsh-jha-dev** [comment]
> LGTM. Thank you for the submission. Can you edit the PR to develop branch?

Done

**Comment by avneesh-akto** [comment]
Hi @adarsh-jha-dev plz remove this commit "[Update TemplateStringEditor.jsx](https://github.com/akto-api-security/akto/pull/664/commits/cfbc7598f58f532555e56be62e4cb429abc459b7)" and make a new PR

**Comment by adarsh-jha-dev** [comment]
> Hi @adarsh-jha-dev plz remove this commit "[Update TemplateStringEditor.jsx](https://github.com/akto-api-security/akto/pull/664/commits/cfbc7598f58f532555e56be62e4cb429abc459b7)" and make a new PR

Yes yes on it, actually i was solving another issue assigned to me, that's why this happened.

**Comment by adarsh-jha-dev** [comment]
Hey @avneesh-akto , i have opened a new PR for this as #678

**Pull request closed without merging**
